### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by jekyl32** [algolia/jquery-block_ellipsis#1]
Hi

Please make some update function to update counter after remove or add item via js.

Maybe some function or option to tell that the block should be default expanded via update function.

**Comment by vvo** [comment]
Can you more precisely define the API changes you would like to see?

maybe @Jerskouille?

**Comment by Jerska** [comment]
I'm indeed really not sure to understand what you're asking for.
Could you describe a bit more your use-case and what you're trying to achieve @jekyl32 ?

If your goal is to re-render a show more after something has been added to its DOM, we could indeed probably expose a function which would work along the lines of the code used when the page is resized:
https://github.com/algolia/jquery-block_ellipsis/blob/57c278ad33b80c1dbd49d042920cf76ab928ab29/src/block_ellipsis.js#L211-L215

**Comment by jekyl32** [comment]
OK you can close this ticket. I did it. It works great !!!
Thanks.
